# Default values for helloworld-ms.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

serviceType: ClusterIP
servicePort: 80
containerPort: 8080
component: "helloworld-ms"
replicas: 3
image: "quay.io/lachie83/helloworld-ms"
imageTag: "latest"
imagePullPolicy: "Always"
## If  you have a private registry you specify a secret to use
#imagePullSecrets:
cpu: "10m"
memory: "128Mi"
## Ingress settings
ingress:
  enabled: true
  hostname: helloworld-ms.acs.az.com.foo
  annotations:
     kubernetes.io/ingress.class: nginx
     kubernetes.io/tls-acme: "true"
  tls: true
## PodDisruptionBudget
pdb:
  enabled: false
  minAvailable: 2
